### ISSUE TITLE
GET fcluns - Failed to HBA ID, Invalid HBA ID

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/gingers390x#10]
Curl command failed with below error: 

curl -u root -H "Content-Type: application/json" -H "Accept:application/json" "http://localhost:8010/plugins/gingers390x/fcluns?type=tape"
Enter host password for user 'root':
{
  "reason":"GS390XSTG00005: Failed to HBA ID, Invalid HBA ID",
  "code":"400 Bad Request"
}

**Comment by harche** [comment]
I will be working on this issue

**Comment by harche** [comment]
The fix works fine.
