### ISSUE TITLE
Storage →FCP Tape Devices API does not return any data

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/gingers390x#11]
Under Storage tab open FCP Tape Devices it returns following error
API : /plugins/gingers390x/lstapes

Error : {
  "reason":"GS390XSTG00017: Unable to execute lstape, GS390XSTG00016: Unable to uuid for tape device
, ",
  "code":"500 Internal Server Error"
} 
![fcp_tape_devoces_59 1](https://cloud.githubusercontent.com/assets/511072/12195994/6c3eaf50-b621-11e5-8e8c-61922e4518ea.png)

**Comment by harche** [comment]
I will be working on this issue

**Comment by pkulkark** [comment]
I have a working patch for this issue. I will be sending it soon.

**Comment by pkulkark** [comment]
This issue can be closed as the fix works fine.
