### ISSUE TITLE
FCP Device not listing properly 

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/gingers390x#14]
Storage →Storage Devices → Add FCP Device Listing
1. Records are not listed properly, headers number are 4 but data column are only 3 
2. While page is loading all the buttons on page is enabled
3. pop up page finish border bottom is not properly align

![fcp_device_listing_25 1](https://cloud.githubusercontent.com/assets/511072/12215023/5dcb2afc-b6d0-11e5-8e81-f5996cb3f801.png)

**Comment by harche** [comment]
This issue is fixed now.
