### ISSUE TITLE
Enabling ECKD decive does not add in Storage device listing

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/gingers390x#22]
Storage →Storage Devices → Add ECKD Device Listing → Enable
1. successful message appears on parent page
2. Parent records (Storage Device listing) are not updated even if we refresh the page

**Comment by sureshab** [comment]
@rajatgupta21  

i just sent a patch for point 2.

**Comment by sureshab** [comment]
the fix works fine,,issue can be closed
