### ISSUE TITLE
Add → FCP SAN Adapter Device does not update SAN Adapters listing

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/gingers390x#24]
Storage →SAN Adapters Add → FCP SAN Adapter Device Listing → Enable
1. successful message does not appear on page
2. Parent record is not updated even if we refresh the page

**Comment by archu-s** [comment]
Notices one more issue: 
3. On successful removal of SAN Adapter from blacklist does not refreshed the FCP SAN Adapter Device Listing.

**Comment by sureshab** [comment]
@rajatgupta21 
just sent a patch for point 2

**Comment by rajatgupta21** [comment]
Sent patch for Fixing message related issue and also corrected auto refresh issue.

**Comment by rajatgupta21** [comment]
Fix works fine
