### ISSUE TITLE
NW UI: subchannels is not getting displayed in network setting panel

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/gingers390x#26]
subchannels is not getting displayed in network setting panel, even if RESTful API returns SUBCHANNELS.
Currently UI implementation, reads "SUBCHANNEL" from JSON response instead of "SUBCHANNEL"

**Comment by archu-s** [comment]
Need to be raised in ginger plugin. I will raise it in ginger and this can be closed here.

**Comment by potula-chandra** [comment]
@danielhb Please close the ticket as this is not valid for ginger s390x
