### ISSUE TITLE
Core dump due to memory leak while activating more than 3 networks in a loop.

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/gingers390x#3]
Core dump due to memory leak while activating more than 3 networks in a loop, due to Augaes instance used statically. This stops wokd service.

**Comment by sureshab** [comment]
hi @archu-s ,
I am looking at this issue, will be providing patch soon if required.

**Comment by archu-s** [comment]
patch resolves the issue. So it can be closed now.
