### ISSUE TITLE
Message displayed while removing a storage device is not clear.

### ISSUE THREAD

**Issue by pawankg** [kimchi-project/gingers390x#32]
Started format of a ECKD storage device via the Storage device format option from UI, and while its going on switched tab and come back to storage tab. Selected the same device whose formatting is going in background, I got remove option. And no indication of background formatting going on for the listed devices.
When tried to remove the same device, does not show if remove is going on in background and then after a while got failure message but does not specified the reason of the failure. 

This fix is required to fix issue #188 of ginger ( Storage UI: Switch tab while formatting is going on, allow format/remove the same device and fails with no proper reason specified).

**Comment by sureshab** [comment]
@pawankg 
could  please verify if the issue is fixed,,and close the issue?

**Comment by pawankg** [comment]
This issue is fixed so closing the issue.
