### ISSUE TITLE
make check local is failing with undefined name 'sg_dev' in model/utils.py

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/gingers390x#8]
contrib/check_i18n.py ./i18n.py 
Checking for invalid i18n string...
Checking for invalid i18n string successfully
find . -path './.git' -prune -type f -o \
    -name '_.py' -o -name '_.py.in'  | xargs /usr/bin/pyflakes | \
    while read LINE; do echo "$LINE"; false; done
./model/utils.py:130: undefined name 'sg_dev'
Makefile:1015: recipe for target 'check-local' failed
make: **\* [check-local] Error 1

**Comment by sureshab** [comment]
@archu-s 
please refer issue #7.

**Comment by archu-s** [comment]
Thanks @sureshab.
This issue can be closed as similar to issue #7.
