### ISSUE TITLE
NW: TYPE is not added to ifcfg file while configuring the network adapters.

### ISSUE THREAD

**Issue by archu-s** [kimchi-project/gingers390x#9]
1) Configured a netowrk adapter using below curl command.
curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X POST -d {} 'https://9.152.151.67:8001/plugins/gingers390x/nwdevices/0.0.1f10/configure'
Enter host password for user 'root':
{
  "status":"running",
  "message":"",
  "id":"29",
  "target_uri":"/plugins/gingers390x/nwdevices/0.0.1f10/configure"
curl -k -u root:pass4root -H "Content-Type: application/json" -H "Accept: application/json" -X GET 'https://127.0.0.1:8001/plugins/gingers390x/tasks/29'
{
  "status":"finished",
  "message":"Successfully configured network device 0.0.1f10",
  "id":"29",
  "target_uri":"/plugins/gingers390x/nwdevices/0.0.1f10/configure"
}

2) ifcfg file created with content as 
DEVICE=enccw0.0.1f10
ONBOOT=yes
NETTYPE=qeth
SUBCHANNELS=0.0.1f10,0.0.1f11,0.0.1f12

Its a discuss call to either add TYPE as Ethernet in gingers390x while configuring network or GET for cfginterface should return NETTYPE for s390x architecture(issue #132 in ginger) as s390x architecture mandates to have NETTYPE in ifcfg file. 

I will vote for NETTYPE to be return by GET cfginterface in ginger for s390x architecture.

**Comment by sureshab** [comment]
Ifcfg file is created to persist a network triplet when it is configured. The purpose is to have, minimum attributes written into ifcfg file to make the device persist, without conflicting with other attributes. hence TYPE is not added into file.

All the physical devices are of type Ethernet,, I could add it to ifcfg file to while persisting it.

**Comment by sureshab** [comment]
I will send a patch for this fix.

**Comment by archu-s** [comment]
Issue fixed with the patch, it can be closed.
